#!/usr/bin/env bash
# Sovereign macOS SDK provisioning for the BearBrowser Gecko build.
#
# WHY THIS EXISTS
# Firefox's build wants a macOS SDK. Mozilla's build fetches it via
# taskcluster/scripts/misc/unpack-sdk.py, which — when MOZ_AUTOMATION is set —
# rewrites the download URL to `http://taskcluster/tooltool...`, an address that
# only resolves inside Mozilla's CI network (HTTP 403 for everyone else). The
# non-automation fallback is Apple's swcdn.apple.com, a public CDN whose per-SDK
# URLs rot over time. Depending on either is exactly the external-CDN coupling our
# design thesis rejects (see: vendor, don't reference a CDN).
#
# WHAT THIS DOES (sovereign + reproducible)
# Every macOS build machine already carries a LICENSED macOS SDK inside the Xcode
# Command Line Tools. We package THAT into the same tarball layout Mozilla's
# toolchain uses (MacOSX<ver>.sdk.tar.zst), hash it (sha512), extract it to a
# stable local toolchain root, and record a manifest. The build then consumes our
# provisioned SDK via --with-macos-sdk and never fetches from Mozilla or Apple.
#
# The packaged artifact is ALSO pushed (best-effort) to our own sovereign artifact
# store so every builder pulls the identical, pinned SDK — reproducible across
# runners and independent of the runner's Xcode drift. That upload is optional
# (Phase 2): the local path this script prints is sufficient for the build.
#
#   eval "$(scripts/provision-macos-sdk.sh)"    # exports BEARBROWSER_MACOS_SDK
#
# On success it prints, to stdout, a single line:
#   export BEARBROWSER_MACOS_SDK=/path/to/MacOSX.sdk
# and writes everything else (logs) to stderr, so it is eval-safe.
set -uo pipefail

log() { printf '[provision-macos-sdk] %s\n' "$*" >&2; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="${BEARBROWSER_HOME:-$(cd "$script_dir/.." && pwd)}"

# Where our sovereign SDK toolchain lives on the build machine. Stable across
# builds so it can be cached.
sdk_root="${BEARBROWSER_SDK_ROOT:-${MOZBUILD_STATE_PATH:-$HOME/.mozbuild}/bearbrowser-macos-sdk}"
# Our sovereign artifact store (same bucket the Linux build already uses).
gcs_prefix="${BEARBROWSER_SDK_GCS:-gs://sourceos-artifacts-socioprophet/bearbrowser/toolchains/macos-sdk}"
manifest="$repo_root/packaging/macos/sdk-source.env"

if [ "$(uname -s)" != "Darwin" ]; then
  log "FATAL: macOS only"; exit 1
fi

# 1. Locate the licensed system SDK from the Command Line Tools / Xcode.
sys_sdk="$(xcrun --show-sdk-path 2>/dev/null || true)"
sdk_ver="$(xcrun --show-sdk-version 2>/dev/null || true)"
if [ -z "$sys_sdk" ] || [ ! -d "$sys_sdk" ]; then
  log "FATAL: no system macOS SDK (install Xcode Command Line Tools: xcode-select --install)"
  exit 1
fi
log "system SDK: $sys_sdk (version $sdk_ver)"

sdk_name="MacOSX${sdk_ver}.sdk"
provisioned="$sdk_root/$sdk_name"
tarball="$sdk_root/${sdk_name}.tar.zst"

# 2. If we've already provisioned this exact SDK version, reuse it (cache hit).
if [ -d "$provisioned" ] && [ -f "$provisioned/SDKSettings.plist" ]; then
  log "reusing already-provisioned SDK: $provisioned"
  printf 'export BEARBROWSER_MACOS_SDK=%s\n' "$provisioned"
  exit 0
fi

mkdir -p "$sdk_root"

# 3. Package the licensed SDK into the Mozilla toolchain-artifact layout
#    (a .tar.zst whose top entry is MacOSX<ver>.sdk/). zstd ships with macOS 12+.
log "packaging licensed SDK -> $tarball"
sdk_parent="$(dirname "$sys_sdk")"
sdk_leaf="$(basename "$sys_sdk")"
if command -v zstd >/dev/null 2>&1; then
  # Fast level: this is a build toolchain we extract immediately, not a max-
  # compression distribution artifact. -T0 = all cores.
  ( cd "$sdk_parent" && tar -cf - "$sdk_leaf" ) | zstd -q -3 -T0 -o "$tarball.tmp" \
    && mv "$tarball.tmp" "$tarball"
else
  # Fallback: gzip if zstd is somehow unavailable.
  tarball="$sdk_root/${sdk_name}.tar.gz"
  ( cd "$sdk_parent" && tar -czf "$tarball.tmp" "$sdk_leaf" ) && mv "$tarball.tmp" "$tarball"
fi

# 4. Extract our own copy to the stable provisioned path (rename leaf -> versioned).
log "extracting -> $provisioned"
tmp_ex="$sdk_root/.extract.$$"
rm -rf "$tmp_ex"; mkdir -p "$tmp_ex"
if [[ "$tarball" == *.zst ]]; then
  zstd -q -d -c "$tarball" | tar -x -C "$tmp_ex"
else
  tar -xzf "$tarball" -C "$tmp_ex"
fi
rm -rf "$provisioned"
mv "$tmp_ex/$sdk_leaf" "$provisioned"
rm -rf "$tmp_ex"

# 5. Hash + manifest (pin for reproducibility + verification).
sha="$(shasum -a 512 "$tarball" | awk '{print $1}')"
mkdir -p "$(dirname "$manifest")"
{
  echo "# BearBrowser sovereign macOS SDK — generated by scripts/provision-macos-sdk.sh"
  echo "# The build consumes this SDK (packaged from licensed Xcode CLT), NOT Mozilla's"
  echo "# auth-gated toolchain proxy or Apple's swcdn CDN."
  echo "BEARBROWSER_MACOS_SDK_VERSION=\"$sdk_ver\""
  echo "BEARBROWSER_MACOS_SDK_ARTIFACT=\"${sdk_name}.tar.zst\""
  echo "BEARBROWSER_MACOS_SDK_SHA512=\"$sha\""
  echo "BEARBROWSER_MACOS_SDK_GCS=\"$gcs_prefix/${sdk_name}.tar.zst\""
} > "$manifest"
log "manifest -> $manifest (sha512=${sha:0:16}...)"

# 6. Best-effort push to our sovereign artifact store (Phase 2: reproducible pull
#    for every builder). Non-fatal — the local provisioned SDK is enough to build.
if command -v gcloud >/dev/null 2>&1; then
  if gcloud storage cp "$tarball" "$gcs_prefix/${sdk_name}.tar.zst" >/dev/null 2>&1; then
    log "vendored to sovereign store: $gcs_prefix/${sdk_name}.tar.zst"
  else
    log "note: sovereign-store upload skipped (no creds / offline) — local SDK still used"
  fi
else
  log "note: gcloud not present — skipping sovereign-store upload (local SDK still used)"
fi

log "provisioned SDK ready: $provisioned"
printf 'export BEARBROWSER_MACOS_SDK=%s\n' "$provisioned"
